import React, { useState } from 'react';
import { PROFS } from '../../data/professions';
import { cF, mHP } from '../../utils/character';
import BestiaryEditor from './BestiaryEditor';
import DonatePage from './DonatePage';
import GameView from '../GameView';
import LoreEditor from './LoreEditor';

function GMPanel(pr){var _s=useState(null);var sid=_s[0];var sS=_s[1];var _sl=useState(false);var sl=_sl[0];var sSL=_sl[1];
var showBest=pr.showBest||false;var sShowBest=pr.setShowBest||function(){};
var sel=pr.characters.find(function(c){return c._fbId===sid});
if(sel)return <GameView char={sel} save={function(d){pr.saveChar(sel._fbId,d)}} onBack={function(){sS(null)}} isGM={true} logs={pr.logs} addLog={pr.addLog} lore={pr.lore} mapData={pr.mapData} saveMap={pr.saveMap} characters={pr.characters} spawned={pr.spawned} saveSpawned={pr.saveSpawned} pendAtk={pr.pendAtk} clearPendingAttack={pr.clearPendingAttack} room={pr.roomCode} savePendingAttack={pr.savePendingAttack}/>;
if(sl)return(<div style={{flex:1,display:"flex",flexDirection:"column"}}><div style={{padding:"8px 10px",borderBottom:"2px solid #c084fc28",background:"#1f1330",display:"flex",alignItems:"center",gap:6}}><button onClick={function(){sSL(false)}} style={{background:"none",border:"none",fontSize:14,cursor:"pointer",color:"#a89a82"}}>←</button><span style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:14,color:"#7c3aed"}}>📚 Лорбук</span></div><div style={{flex:1,padding:8,overflowY:"auto"}}><LoreEditor lore={pr.lore} saveLore={pr.saveLore} mapData={pr.mapData} saveMap={pr.saveMap} characters={pr.characters}/></div></div>);
if(showBest)return <BestiaryEditor npcTempl={pr.npcTempl} saveNpcTempl={pr.saveNpcTempl} spawned={pr.spawned} saveSpawned={pr.saveSpawned} onBack={function(){sShowBest(false)}} addLog={pr.addLog} characters={pr.characters} roomCode={pr.roomCode} savePendingAttack={pr.savePendingAttack} clearPendingAttack={pr.clearPendingAttack} pendAtk={pr.pendAtk} logs={pr.logs}/>;
return(<div style={{flex:1,display:"flex",flexDirection:"column"}}><div style={{padding:"8px 10px",borderBottom:"2px solid #c084fc28",background:"#1f1330"}}><div style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:16,color:"#7c3aed",textAlign:"center"}}>🎭 ГМ</div></div><div style={{flex:1,padding:8,overflowY:"auto",display:"flex",flexDirection:"column",gap:6}}>
<button onClick={function(){sSL(true)}} style={{width:"100%",padding:10,borderRadius:9,border:"2px solid #8b5cf630",background:"#1f1330",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:"#7c3aed",cursor:"pointer"}}>📚 Лорбук</button>
<button onClick={function(){sShowBest(true)}} style={{width:"100%",padding:10,borderRadius:9,border:"2px solid #ef444430",background:"#2a1414",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:"#ef4444",cursor:"pointer"}}>👹 Бестиарий / NPC</button>
{pr.characters.length===0&&<div style={{textAlign:"center",padding:20,color:"#a89a82"}}>Ожидаем...</div>}
{pr.characters.map(function(c){var inf=cF(c);var pf=PROFS.find(function(p){return p.id===c.profId})||PROFS[0];var mx=c.hpOv||mHP(inf.fs);var ch=c.curHp!==null&&c.curHp!==undefined?c.curHp:mx;return(<div key={c._fbId} style={{background:"#1d1a14",border:"2px solid #c084fc18",borderRadius:9,padding:"7px 9px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:3}}><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:12}}>{c.name||"?"} <span style={{fontSize:8,color:"#a89a82"}}>{pf.name} Ур.{c.level}</span>{c.active&&<span style={{fontSize:7,background:"#10b981",color:"#fff",borderRadius:3,padding:"1px 4px",marginLeft:4}}>В ИГРЕ</span>}</span><div style={{display:"flex",gap:2}}><button onClick={function(){pr.saveChar(c._fbId,Object.assign({},c,{active:!c.active}))}} style={{padding:"3px 7px",borderRadius:5,border:"1px solid "+(c.active?"#10b98140":"#e8e0d4"),background:c.active?"#ecfdf5":"#fefdfb",fontWeight:700,fontSize:8,color:c.active?"#065f46":"#8b7e6a",cursor:"pointer"}}>{c.active?"✓ Активен":"В игру"}</button><button onClick={function(){sS(c._fbId)}} style={{padding:"3px 8px",borderRadius:5,border:"1px solid #7c3aed28",background:"#1f1330",fontWeight:700,fontSize:9,color:"#7c3aed",cursor:"pointer"}}>Открыть</button></div></div>
<div style={{fontSize:9}}>{"❤️ "+ch+"/"+mx+" 🔥 "+(inf.fs.WILL||0)}</div>
<div style={{display:"flex",gap:2,marginTop:3,flexWrap:"wrap"}}><button onClick={function(){pr.saveChar(c._fbId,Object.assign({},c,{level:c.level+1,lvlPts:(c.lvlPts||0)+2}))}} style={{padding:"3px 6px",borderRadius:4,border:"1px solid #10b98128",background:"#0e2018",fontSize:8,fontWeight:700,color:"#34d399",cursor:"pointer"}}>⬆️+1</button><button onClick={function(){pr.saveChar(c._fbId,Object.assign({},c,{curHp:c.hpOv||mHP(cF(c).fs),curWill:c.willOv||cF(c).fs.WILL||1}))}} style={{padding:"3px 6px",borderRadius:4,border:"1px solid #10b98128",background:"#0e2018",fontSize:8,fontWeight:700,color:"#34d399",cursor:"pointer"}}>💤</button>{[-5,-1,1,5].map(function(d){return <button key={d} onClick={function(){var mx2=c.hpOv||mHP(cF(c).fs);var cur=c.curHp!==null&&c.curHp!==undefined?c.curHp:mx2;pr.saveChar(c._fbId,Object.assign({},c,{curHp:Math.max(0,Math.min(mx2,cur+d))}))}} style={{padding:"3px 5px",borderRadius:4,border:"1px solid #ef444420",background:d<0?"#fef2f2":"#ecfdf5",fontSize:8,fontWeight:700,color:d<0?"#ef4444":"#10b981",cursor:"pointer"}}>{"HP"+(d>0?"+":"")+d}</button>})}<button onClick={function(){if(window.confirm("Удалить "+c.name+"?"))pr.deleteChar(c._fbId)}} style={{padding:"3px 6px",borderRadius:4,border:"1px solid #ef444440",background:"#2a1414",fontSize:8,fontWeight:700,color:"#ef4444",cursor:"pointer"}}>🗑️ Удалить</button></div></div>)})}
<div style={{border:"2px solid #322d24",borderRadius:9,padding:"7px 8px",background:"#1d1a14"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4}}><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:12}}>📜 Общий лог</span><button onClick={function(){if(window.confirm("Очистить все логи?"))pr.clearLogs()}} style={{fontSize:8,background:"#2a1414",border:"1px solid #ef444420",borderRadius:4,padding:"2px 6px",cursor:"pointer",color:"#ef4444",fontWeight:700}}>🗑️ Очистить</button></div><div style={{maxHeight:250,overflowY:"auto",display:"flex",flexDirection:"column",gap:2}}>{(pr.logs||[]).length===0&&<div style={{textAlign:"center",padding:10,color:"#a89a82",fontStyle:"italic",fontSize:9}}>Пусто</div>}{(pr.logs||[]).map(function(l,i){var bgc=l.type==="magic_fail"?"#fee2e2":l.type==="magic"?"#fdf4ff":l.type==="rest"?"#ecfdf5":l.type==="dodge"?"#f0fdf4":l.type==="zone"?"#fffbeb":l.type==="hit"?"#eff6ff":l.type==="dmg_npc"?"#fef2f2":l.type==="dmg"?"#fef2f2":l.type==="spawn"?"#fdf4ff":"#fefdfb";return <div key={i} style={{background:bgc,border:"1px solid #322d2420",borderRadius:5,padding:"4px 6px",fontSize:9,animation:i===0?"slideIn 0.3s":"none"}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:700,color:"#ece5d8"}}>{l.who||"?"}</span>{l.ts&&<span style={{fontSize:7,color:"#c2b69e"}}>{new Date(l.ts).toLocaleTimeString()}</span>}</div><div style={{color:"#b3a890",marginTop:1}}>{l.label}</div>{l.detail&&<div style={{fontSize:8,color:"#9a8f7c",fontFamily:"monospace"}}>{l.detail}</div>}{l.total>0&&<div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:l.type==="magic_fail"?"#dc2626":"#2d2a24"}}>{"= "+l.total}</div>}</div>})}</div></div>
</div></div>)}


/* ── DonatePage ── */

export default GMPanel;
