import React, { useState } from 'react';
import { LORE_CH } from '../../data/lore';
import LoreEditor from '../gm/LoreEditor';
import MapView from './MapView';

function LibTab(pr){var lore=pr.lore||{};var _s=useState(null);var oid=_s[0];var sO=_s[1];var ch=oid?LORE_CH.find(function(x){return x.id===oid}):null;
if(ch&&ch.id==="map")return <div style={{display:"flex",flexDirection:"column",gap:8}}><button onClick={function(){sO(null)}} style={{alignSelf:"flex-start",padding:"4px 10px",borderRadius:6,border:"2px solid #e8e0d4",background:"#fefdfb",fontWeight:700,fontSize:10,cursor:"pointer"}}>← Назад</button><MapView mapData={pr.mapData} saveMap={pr.saveMap} characters={pr.characters} isGM={pr.isGM} charId={pr.charId}/></div>;
if(ch){var ct=lore[ch.id]||"";return(<div style={{display:"flex",flexDirection:"column",gap:8}}><button onClick={function(){sO(null)}} style={{alignSelf:"flex-start",padding:"4px 10px",borderRadius:6,border:"2px solid #e8e0d4",background:"#fefdfb",fontWeight:700,fontSize:10,cursor:"pointer"}}>← Назад</button><div style={{textAlign:"center"}}><div style={{fontSize:28}}>{ch.icon}</div><div style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:15,color:ch.color,marginTop:4}}>{ch.title}</div></div>{ct.trim()?<div style={{background:"#fff",border:"2px solid #e8e0d4",borderRadius:10,padding:"12px 10px"}}>{ct.split("\n").map(function(l,i){if(l.startsWith("### "))return <div key={i} style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,marginTop:8}}>{l.slice(4)}</div>;if(l.startsWith("## "))return <div key={i} style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:15,color:ch.color,marginTop:10}}>{l.slice(3)}</div>;if(l.startsWith("# "))return <div key={i} style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:17,marginTop:12}}>{l.slice(2)}</div>;if(l.startsWith("---"))return <hr key={i} style={{border:"none",borderTop:"1px solid #e8e0d4",margin:"8px 0"}}/>;if(l.startsWith("- "))return <div key={i} style={{fontSize:10,paddingLeft:12}}>• {l.slice(2)}</div>;if(!l.trim())return <div key={i} style={{height:6}}/>;return <div key={i} style={{fontSize:10,lineHeight:1.6}}>{l}</div>})}</div>:<div style={{textAlign:"center",padding:20,color:"#8b7e6a"}}><div style={{fontSize:24}}>📜</div><div style={{fontSize:12,fontWeight:700}}>Готовится</div></div>}</div>)}
return(<div style={{display:"flex",flexDirection:"column",gap:5}}><div style={{textAlign:"center",padding:"8px 0"}}><div style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:16}}>📚 Лорбук</div></div>{LORE_CH.map(function(ch){var has=lore[ch.id]&&lore[ch.id].trim();return <button key={ch.id} onClick={function(){sO(ch.id)}} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 10px",borderRadius:9,border:"2px solid "+ch.color+"18",background:ch.color+"06",cursor:"pointer",textAlign:"left",opacity:has?1:0.6}}><div style={{width:30,height:30,borderRadius:6,background:ch.color+"15",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,flexShrink:0}}>{ch.icon}</div><div style={{flex:1}}><div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10}}>{ch.title}</div></div><span style={{color:"#c4b8a4"}}>›</span></button>})}</div>)}

/* ── LoreEditor ── */

export default LibTab;
